#!/usr/bin/env bash
# Install nginx on web server

# Update package list and install nginx
sudo apt-get -y update
sudo apt-get -y install nginx

# Allow Nginx through the firewall (ufw)
sudo ufw allow "Nginx HTTP"

# Create a simple HTML page with the string "Hello World!"
echo 'Hello World!' | sudo tee /var/www/html/index.nginx-debian.html > /dev/null

# Restart Nginx to apply changes
sudo service nginx restart

