#!/usr/bin/env bash
# configures an Nginx server so that /redirect_me is redirecting to another page

# Check if the script is run with root privileges
if [ "$(id -u)" -ne 0 ]; then
    echo "Please run the script as root or using sudo."
    exit 1
fi

# Update package list and install nginx
apt-get -y update
apt-get -y install nginx

# Allow Nginx through the firewall (ufw)
ufw allow 'Nginx HTTP'

# Create a simple HTML page with the string "Hello World!"
echo 'Hello World!' > /var/www/html/index.nginx-debian.html

# Add redirection configuration to the Nginx default site configuration
sed -i '/listen 80 default_server;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

# Restart Nginx to apply the changes
service nginx restart

# Display a message indicating successful configuration
echo "Nginx redirection configured successfully. /redirect_me now redirects to https://www.youtube.com/watch?v=QH2-TGUlwu4."
