#!/usr/bin/env bash
# Installs and sets up HAProxy

# Check if the script is run as root
if [[ $EUID -ne 0 ]]; then
    echo "Error: This script must be run as root. Use 'sudo $0'." >&2
    exit 1
fi

# Install HAProxy
apt-get install -y software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-1.8
apt-get -y update
apt-get install -y haproxy=1.8.*

# Enable HAProxy service
echo "ENABLED=1" > /etc/default/haproxy

# Configure HAProxy
cat <<EOF > /etc/haproxy/haproxy.cfg
listen load_balancer
    bind *:80
    mode http
    balance roundrobin
    option httpclose
    option forwardfor
    server 477562-web-01 52.87.28.205:80 check
    server 477562-web-02 34.229.69.104:80 check
EOF

# Start HAProxy service
systemctl start haproxy
