#!/usr/bin/env bash

# Install HAProxy
apt-get update
apt-get install -y software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.4
apt-get -y update
apt-get install -y haproxy

# Configure HAProxy
cat <<EOF > /etc/haproxy/haproxy.cfg
global
    log /dev/log local0
    log /dev/log local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log global
    mode http
    option httplog
    option dontlognull
    timeout connect 5000
    timeout client 50000
    timeout server 50000

frontend load_balancer
    bind *:80
    mode http
    default_backend web_servers

backend web_servers
    balance roundrobin
    option httpclose
    option forwardfor
    server 477562-web-01 52.87.28.205:80 check
    server 477562-web-02 34.229.69.104:80 check
EOF

# Restart HAProxy
systemctl restart haproxy
